[build]
  command = "npm run build:combined && npm run site:build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses for 1 hour  
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache HTML pages for 1 hour
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
